DROP DATABASE IF EXISTS `%DB_NAME%`;
CREATE DATABASE `%DB_NAME%`;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON `%DB_NAME%` . * TO '%DB_USER%'@'%DB_HOST%';
